[package]
name = "rew"
version = "1.5.5"
edition = "2021"


[dependencies]
deno_core = "0.339.0"
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.96"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
regex = "1.10"