[package]
name = "rew"
version = "1.5.5"
edition = "2021"


[dependencies]
deno_core = "0.338.0"
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.96"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
regex = "1.10"
uuid = { version = "1.4", features = ["v4"] }
once_cell = "1.18"
base64 = "0.21.0"
deno_ffi = "0.180.0"
deno_web = "0.224.0"
deno_permissions = "0.52.0"
deno_webidl = "0.193.0"
deno_console = "0.193.0"
deno_url = "0.193.0"
#deno_error = "0.5.5"
#denort_helper = "0.1.0"
#libffi = "4.1.0"
#libffi-sys = "3.3.1"
#thiserror = "2.0.12"
#num-bigint = "0.4.6"
#memmap2 = "0.9.5"
#dlopen2 = "0.7.0"
#cranelift = "0.117.0"
#cranelift-native = "0.117.0"