[package]
name = "rew"
version = "0.0.1"
edition = "2021"
authors = ["makano"]
description = "A mini runtime for coffeescript"
repository = "https://github.com/kevinj045/rew"
readme = "README.md"
keywords = ["cli", "rew", "coffeescript"]
categories = ["command-line-utilities"]
include = [
  "src/**",
  "lib/**",
  "Cargo.toml",
  "README.md",
]

[lib]
name = "rew"
path = "src/lib.rs"

[dependencies]
deno_core = "0.338.0"
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.96"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
serde_yaml = "0.9"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
regex = "1.10"
uuid = { version = "1.4", features = ["v4"] }
once_cell = "1.18"
base64 = "0.21.0"
deno_ffi = "0.180.0"
deno_web = "0.224.0"
deno_permissions = "0.52.0"
deno_webidl = "0.193.0"
deno_console = "0.193.0"
deno_url = "0.193.0"