[package]
name = "rew_bindgen_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "2", features = ["full"] }
quote = "1"
ctor = "0.2"
rew_bindgen = { path = "../rew_bindgen_a" }
libc = "0.2"
serde_json = "1.0"
