[package]
name = "rew_bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
once_cell = "1"
ctor = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"
